spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kindergarten
    password: pass
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

  mvc:
    format:
      date: iso
      date-time: iso